# Generated by Django 2.2.6 on 2019-10-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ad_haha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='haha',
        ),
    ]
