# Generated by Django 2.2.6 on 2019-10-31 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_ad_haha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否是Active'),
        ),
        migrations.AddField(
            model_name='ad',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='文章创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200, verbose_name='文章摘要'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='youtube_video_link',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='YouTube视频Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='友情链接创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
