# Generated by Django 2.2.6 on 2019-10-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191031_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='youtube_video_link',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube视频Url'),
        ),
    ]
